fix the functions/config finding bit

diff --git a/src/bootstrap b/src/bootstrap
--- a/src/bootstrap
+++ b/src/bootstrap
@@ -11,15 +11,17 @@
 SCRIPT_NAME=$(basename $0)
 INITIAL_DIR=$(pwd)
  SCRIPT_DIR=$(dirname $0)
-if ! echo $SCRIPT_DIR | egrep -q "(^)$INITIAL_DIR" ; then
+if ! echo $SCRIPT_DIR | egrep -q "(^)/" ; then
    BASE_DIR=$INITIAL_DIR/$SCRIPT_DIR
 else
    BASE_DIR=$SCRIPT_DIR
 fi
 
-. $BASE_DIR/../scripts/zmap_functions.sh
+. $BASE_DIR/../scripts/zmap_functions.sh || { echo "Failed to load zmap_functions.sh"; exit 1; }
 set -o history
-. $BASE_DIR/../scripts/build_config.sh
+. $BASE_DIR/../scripts/build_config.sh   || { echo "Failed to load build_config.sh";   exit 1; }
+
+zmap_message_out "Start of script."
 
 ############################################################
 ############################################################
