runconfig to fit in with new build.

diff --git a/src/runconfig b/src/runconfig
--- a/src/runconfig
+++ b/src/runconfig
@@ -3,15 +3,24 @@
 # Noddy script to run configure as alphas + Roys machine are far from standard.
 #
 
-root=`dirname $0`
-script=`basename $0`
+SCRIPT_NAME=$(basename $0)
+INITIAL_DIR=$(pwd)
+ SCRIPT_DIR=$(dirname $0)
+if ! echo $SCRIPT_DIR | egrep -q "(^)/" ; then
+   BASE_DIR=$INITIAL_DIR/$SCRIPT_DIR
+else
+   BASE_DIR=$SCRIPT_DIR
+fi
 
-msgAndExit ()
-{
-  echo "Error: $1"
-  exit 1
-}
+. $BASE_DIR/../scripts/zmap_functions.sh || { echo "Failed to load zmap_functions.sh"; exit 1; }
+set -o history
+. $BASE_DIR/../scripts/build_config.sh   || { echo "Failed to load build_config.sh";   exit 1; }
 
+zmap_message_out "Start of script."
+
+zmap_message_out "Running in $INITIAL_DIR on $(hostname) under $(uname)"
+
+zmap_message_out "cmd line options = '$*'"
 
 opsys=`uname`
 
@@ -34,146 +43,112 @@ case $opsys in
     locals=/nfs/team71/acedb/zmap/prefix/ALPHA/lib/pkgconfig
     PKG_CONFIG_PATH="$locals:/usr/local/gtk2/lib/pkgconfig"
     export PKG_CONFIG_PATH 
+    zmap_message_exit "No longer a supported operating system."
     ;;
 
   Linux )
 
     case `uname -m` in
       
-      x86_64 )
-
-         locals=~zmap/prefix/LINUX_64
-         PATH="$locals/bin:$PATH"
-         export PATH
-
-         PKG_CONFIG_PATH="$locals/lib/pkgconfig"
-         export PKG_CONFIG_PATH
-         LD_LIBRARY_PATH="$locals/lib"
-         export LD_LIBRARY_PATH
-
-         CC_args=''
-         CFLAGS_args='CFLAGS=-Wall'
+	x86_64 )
+	    
+	    locals=~zmap/prefix/LINUX_64
+	    PATH="$locals/bin:$PATH"
+	    export PATH
+	    
+	    PKG_CONFIG_PATH="$locals/lib/pkgconfig"
+	    export PKG_CONFIG_PATH
+	    LD_LIBRARY_PATH="$locals/lib"
+	    export LD_LIBRARY_PATH
+	    
+	    CFLAGS_args='CFLAGS=-Wall'
          # make sure zmap executable has path to foocanvas library.
-         LDFLAGS_args="LDFLAGS=-Xlinker -rpath -Xlinker $locals/lib" 
-         ;;
+	    LDFLAGS_args="LDFLAGS=-Xlinker -rpath -Xlinker $locals/lib" 
+	    ;; # end x86_64
 
-       * )
+	* ) 
 
-         locals=~zmap/prefix/LINUX
-         software=/software/acedb
-         use_slash_software=true
-	 use_gprof=no
-	 
-         # To test a new version of foocanvas uncomment next line and set it to the prefix you installed foocanvas to
-	 foo_test="" #/var/tmp/foocanvas-prefix
-	 # the rest of the code does the rest.
-         
-         if [ "x$use_slash_software" == "xtrue" ] ; then
-             PATH="$software/bin:$locals/bin:$PATH"
-             PKG_CONFIG=$software/bin/pkg-config
+	    # For some reason aceconn isn't installed in GTK_PREFIX
+	    # This should change asap. Production foocanvas is!
+	    if [ "x$ACECONN_PREFIX" != "x" ]; then 
+		zmap_register_prefix_in_env $ACECONN_PREFIX
+		zmap_register_prefix_as_rpath $ACECONN_PREFIX
+	    fi
+	    # We need to find freetype2.pc in here. No idea why.
+	    PKG_CONFIG_PATH="/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
 
-             # To test a new version of foocanvas add the directory containing its pkgconfig file to the
-             # front of this lot....
-             PKG_CONFIG_PATH="$software/lib/pkgconfig:/usr/lib/pkgconfig:$locals/lib/pkgconfig"
-
-             # To test a new version of foocanvas add the directory containing its library
-             # front of this lot....
-             LD_LIBRARY_PATH="$software/lib:$locals/lib"
-
-             # make sure zmap executable has path to foocanvas library.
-             # To test a new version of foocanvas add its "-L$HOME/ZMap/ZMap_Curr/local/lib -lfoocanvas" to
-             # the end of this lot and add -XLinker flags (-Xlinker -rpath -Xlinker $HOME/ZMap/ZMap_Curr/local/lib)
-             # to the front.
-             local_LDFLAGS="-Xlinker -rpath -Xlinker $software/lib -L$software/lib  -Xlinker -rpath -Xlinker $locals/lib " 
-
-	     if [ "x$foo_test" != "x" ] ; then
-		 PKG_CONFIG_PATH="$foo_test/lib/pkgconfig:$PKG_CONFIG_PATH"
-		 LD_LIBRARY_PATH="$foo_test/lib:$LD_LIBRARY_PATH"
-		 local_LDFLAGS="-Xlinker -rpath -Xlinker $foo_test/lib $local_LDFLAGS -L$foo_test/lib"
-	     fi
-	     if [ "x$use_gprof" == "xyes" ]; then
-		 local_LDFLAGS="-pg $local_LDFLAGS"
-	     fi
-	     LDFLAGS_args="LDFLAGS=$local_LDFLAGS"
-         else
-             PATH="$locals/bin:$PATH"
-             PKG_CONFIG_PATH="$locals/lib/pkgconfig"
-             LD_LIBRARY_PATH="$locals/lib"
-
-             # make sure zmap executable has path to foocanvas library.
-             LDFLAGS_args="LDFLAGS=-Xlinker -rpath -Xlinker $locals/lib" 
-         fi
-
-         export PATH
-         export PKG_CONFIG_PATH
-         export LD_LIBRARY_PATH
-
-         CC_args=''
-         CFLAGS_args='CFLAGS=-Wall -g'
-
-    esac ;;
+	    if [ "x$FOOCANVAS_DEV" == "x$ZMAP_TRUE" ] ; then
+		zmap_register_prefix_in_env $FOOCANVAS_PREFIX
+		zmap_register_prefix_as_rpath $FOOCANVAS_PREFIX
+	    fi
+	    
+	    zmap_register_prefix_in_env $GTK_PREFIX
+	    zmap_register_prefix_as_rpath $GTK_PREFIX
+	    
+	    if [ "x$USE_GPROF" == "x$ZMAP_TRUE" ]; then
+		LDFLAGS="-pg $LDFLAGS"
+	    fi
+	    # Now add LDFLAGS to args so they get through to configure.
+	    LDFLAGS_args="$LDFLAGS $LDFLAGS_args"
+	    ;; # end * 
+    esac 
+    ;; # end Linux
 
  Darwin )
-    # SET PATH TO INCLUDE ~zmap/prefix && /sw/bin in that order
-    # This is for autotools and pkg-config respectively
-    # AceConn ... 
-    # AceConn is installed in /sw/lib && /sw/include for now. A couple of things to note. (manual copy)
-    # The AceConn-1.1.pc file is installed in /sw/lib/pkgconfig/ (manual copy)
-    # The compile of AceConn using the make as setup didn't run ranlib!
-    # Simply run ranlib /sw/lib/libAceConn.a && ranlib /sw/lib/libmd5.a
-    # foocanvas is currently installed in below location...
 
-    echo "*** WARNING *** "
-    echo "*** WARNING *** : Are MAC_MOUNT_POINT && ZMAP_PREFIX set correctly? Edit $0"
-    echo "*** WARNING *** "
+    zmap_register_prefix_in_env $GTK_PREFIX
 
-    foocanvas_prefix=""
-    gtk_prefix="/usr/local"
-    universal_build="yes"
+    CFLAGS_args="-Wall -I$GTK_PREFIX/include"
 
-
-    PATH=$gtk_prefix/bin:$PATH
-    PKG_CONFIG=$gtk_prefix/bin/pkg-config
-    PKG_CONFIG_PATH=$gtk_prefix/lib/pkgconfig
-    ACLOCAL_FLAGS="-I $gtk_prefix/share/aclocal"
-    export LD_LIBRARY_PATH=$gtk_prefix/lib
-
-    CC_args=""
-    CFLAGS_args="CFLAGS=-Wall -I$gtk_prefix/include"
-    local_LDFLAGS="-Xlinker -bind_at_load -L$gtk_prefix/lib"
-
-#    LDFLAGS_args='LDFLAGS=-Xlinker -bind_at_load -L/sw/lib' # added -L/sw/lib for the imac desktop
-
-    if [ "x$foocanvas_prefix" != "x" ]; then 
-	PKG_CONFIG_PATH="$foocanvas_prefix/lib/pkgconfig:$PKG_CONFIG_PATH"
-	local_LDFLAGS="-Xlinker -rpath -Xlinker $foocanvas_prefix/lib $local_LDFLAGS -L$foocanvas_prefix/lib"
+    if [ "x$FOOCANVAS_DEV" != "x$ZMAP_TRUE" ]; then 
+	zmap_register_prefix_in_env $FOOCANVAS_PREFIX
     fi
 
-    if [ "x$universal_build" == "xyes" ]; then
+    if [ "x$UNIVERSAL_BUILD" == "x$ZMAP_TRUE" ]; then
 	SDK=/Developer/SDKs/MacOSX10.4u.sdk
-	CC_args="--disable-dependency-tracking --with-macosx-sdk-path=$SDK"
-	PATH=$SDK/usr/bin:$PATH
+	SPECIFIC_CONFIGURE_ARGS="--disable-dependency-tracking --with-macosx-sdk-path=$SDK --x-includes=$SDK/include --x-libraries=$SDK/lib"
+	if [ -d $SDK/usr/bin ]; then
+	    PATH=$SDK/usr/bin:$PATH
+	fi
     fi
 
-    LDFLAGS_args="LDFLAGS=$local_LDFLAGS"
-    
-    export PKG_CONFIG
-    export PKG_CONFIG_PATH
-    export ACLOCAL_FLAGS
+    LDFLAGS_args="$LDFLAGS $LDFLAGS_args"
     ;;
   * )
-    msgAndExit "unsupported operating system: $opsys" ;;
+    zmap_message_exit "unsupported operating system: $opsys" ;;
 
 esac
 
-echo "$script : Running " $root/configure --enable-shared --disable-static --enable-debug --enable-shtml-doc $CC_args "$CFLAGS_args" "$LDFLAGS_args" "$@"
-echo "=========================================================================="
+CC_param="CC=$CC_args"
+CFLAGS_param="CFLAGS=$CFLAGS_args"
+LDFLAGS_param="LDFLAGS=$LDFLAGS_args"
+
+# Do these here.
+export LD_LIBRARY_PATH
+export LD_RUN_PATH
+export PKG_CONFIG
+export PKG_CONFIG_PATH
+export ACLOCAL_FLAGS
+
+
+
+
+zmap_message_out "Running " \
+    $BASE_DIR/configure \
+    $COMMON_CONFIGURE_ARGS \
+    $SPECIFIC_CONFIGURE_ARGS \
+    $CC_param $CFLAGS_param $LDFLAGS_param "$@"
+
+zmap_message_out "=========================================================================="
 
 
 # run the configure.......watch out for the quoting, sometimes we want the variable to
 # be interpreted as a single cmdline arg, sometimes as multiple ones.
 
-$root/configure --enable-debug --enable-shtml-doc $CC_args "$CFLAGS_args" "$LDFLAGS_args" "$@" || msgAndExit "configure script failed"
+$BASE_DIR/configure \
+$COMMON_CONFIGURE_ARGS \
+$SPECIFIC_CONFIGURE_ARGS \
+"$CFLAGS_param" "$LDFLAGS_param" "$@" || zmap_message_exit "configure script failed."
 
 
 exit 0
